#!/usr/bin/env python3
"""Regenerate CATALOGUE.md from the skills and sets. Never edit it by hand.

    python3 scripts/catalogue.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lint import ROOT, SKILLS, frontmatter, skill_folders  # noqa: E402

SETS = os.path.join(ROOT, "sets")


def first_sentence(text, cap=180):
    text = re.sub(r"\s+", " ", text).strip()
    m = re.search(r"(?<=[a-z0-9)])\.\s+[A-Z]", text)
    s = text[: m.start() + 1] if m else text
    return s if len(s) <= cap else s[:cap].rsplit(" ", 1)[0] + "…"


def main():
    skills = {}  # name -> (relative folder, description, typed)
    for name, rel in skill_folders():
        path = os.path.join(SKILLS, rel, "SKILL.md")
        fields, _ = frontmatter(open(path, encoding="utf-8").read())
        fields = fields or {}
        typed = fields.get("disable-model-invocation", "").lower() == "true"
        skills[name] = (rel, first_sentence(fields.get("description", "")), typed)

    out = ["# Catalogue", "",
           f"{len(skills)} skills. *(typed)* skills run only when you ask for them by name "
           "(`/name` in Claude Code, `$name` in Codex); the rest can also start on their own "
           "when a request matches.", "",
           "> Generated by `python3 scripts/catalogue.py`. Do not edit by hand.", ""]

    sets = sorted(f[:-4] for f in os.listdir(SETS) if f.endswith(".txt")) if os.path.isdir(SETS) else []
    if sets:
        out += ["## Sets", "", "Link a whole set with `agent-skills add <set>`.", "",
                "| Set | Skills |", "|---|---|"]
        for s in sets:
            names = [re.sub(r"#.*", "", l).strip() for l in open(os.path.join(SETS, s + ".txt"))]
            out.append(f"| **{s}** | {', '.join(n for n in names if n)} |")
        out.append("")

    # One table per category folder (skills/<category>/<name>); skills that sit
    # directly under skills/ go in a final "Other" table.
    groups = {}
    for name, (rel, desc, typed) in skills.items():
        category = os.path.dirname(rel) or "other"
        groups.setdefault(category, []).append((name, rel, desc, typed))
    for category in sorted(groups, key=lambda c: (c == "other", c)):
        out += [f"## {category.capitalize()}", "", "| Skill | What it does |", "|---|---|"]
        for name, rel, desc, typed in sorted(groups[category]):
            out.append(f"| [`{name}`](skills/{rel}/SKILL.md){' *(typed)*' if typed else ''} | {desc} |")
        out.append("")

    with open(os.path.join(ROOT, "CATALOGUE.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"Wrote CATALOGUE.md: {len(skills)} skills, {len(sets)} sets")


if __name__ == "__main__":
    main()
