#!/usr/bin/env python3
"""Regenerate CATALOGUE.md from the skills and sets. Never edit it by hand.

    python3 scripts/catalogue.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lint import ROOT, SKILLS, frontmatter  # noqa: E402

SETS = os.path.join(ROOT, "sets")


def first_sentence(text, cap=180):
    text = re.sub(r"\s+", " ", text).strip()
    m = re.search(r"(?<=[a-z0-9)])\.\s+[A-Z]", text)
    s = text[: m.start() + 1] if m else text
    return s if len(s) <= cap else s[:cap].rsplit(" ", 1)[0] + "…"


def main():
    skills = {}
    for folder in sorted(os.listdir(SKILLS)):
        path = os.path.join(SKILLS, folder, "SKILL.md")
        if not os.path.isfile(path):
            continue
        fields, _ = frontmatter(open(path, encoding="utf-8").read())
        fields = fields or {}
        typed = fields.get("disable-model-invocation", "").lower() == "true"
        skills[folder] = (first_sentence(fields.get("description", "")), typed)

    out = ["# Catalogue", "",
           f"{len(skills)} skills. *(typed)* skills run only when you ask for them by name "
           "(`/name` in Claude Code, `$name` in Codex); the rest can also start on their own "
           "when a request matches.", "",
           "> Generated by `python3 scripts/catalogue.py`. Do not edit by hand.", ""]

    sets = sorted(f[:-4] for f in os.listdir(SETS) if f.endswith(".txt")) if os.path.isdir(SETS) else []
    if sets:
        out += ["## Sets", "", "Link a whole set with `agent-skills add <set>`.", "",
                "| Set | Skills |", "|---|---|"]
        for s in sets:
            names = [re.sub(r"#.*", "", l).strip() for l in open(os.path.join(SETS, s + ".txt"))]
            out.append(f"| **{s}** | {', '.join(n for n in names if n)} |")
        out.append("")

    out += ["## Skills", "", "| Skill | What it does |", "|---|---|"]
    for name, (desc, typed) in skills.items():
        out.append(f"| [`{name}`](skills/{name}/SKILL.md){' *(typed)*' if typed else ''} | {desc} |")
    out.append("")

    with open(os.path.join(ROOT, "CATALOGUE.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"Wrote CATALOGUE.md: {len(skills)} skills, {len(sets)} sets")


if __name__ == "__main__":
    main()
